name: Get AWS secrets using reusable workflow

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Call the composite action to retrieve secrets from vault
        uses: Anurag-30/gh-action-workflows/vault-aws-action@main
        with:
          vault-addr: ${{ env.VAULT_ADDR }}
          secret-path: "aws/creds/t"
          vault-token: ${{ secrets.VAULT_TOKEN }}

      - name: List AWS S3 buckets (example)
        run: |
          aws s3 ls
