name: Team Workflow

on:
  push:
    branches:
      - master
env:
  AWS_SECRET_FILE_NAME: 'aws_creds.env'

jobs:
  get-aws-credentials:
    uses: ./.github/workflows/common-workflow.yml
    with:
      vault_url: 'http://15.206.188.81:8200'
      vault_role: 't'
      env-file-name: ${{ env.AWS_SECRET_FILE_NAME }}
    secrets:
      vault_token: ${{ secrets.VAULT_TOKEN }}

  deploy:
    needs: get-aws-credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download Environment File Artifact
        uses: actions/download-artifact@v3
        with:
          name: env-file

      - name: Set Environment Variables from File
        run: |
          # Source the environment file to set the environment variables
          set -o allexport
          source ${{env.AWS_SECRET_FILE_NAME}}
          set +o allexport

      - name: Verify AWS credentials
        run: |
          echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"
          echo "Verifying AWS S3 access..."
          aws s3 ls
